### ISSUE TITLE
electra staat niet op site

### ISSUE THREAD

**Issue by Tibo2008** [hans2103/xper-products.nl#4]
@hans2103 
![image](https://github.com/hans2103/xper-products.nl/assets/167860003/41c09fed-6426-4646-9254-e0454460a92b)
in bovenstaande screenshot zie je dat electro er nie tussen staat op de site zou je deze willen activeren

**Comment by hans2103** [comment]
@Tibo2008 

Met commit https://github.com/hans2103/xper-products.nl/commit/4b3f0c2cb5bf45daa9ce8f275267c1b5f1551ae6 is Electra toegevoegd aan de sidebar. 
Na deployment zal deze ook op de live site zichtbaar zijn.

Bij akkoord mag je dit issue sluiten
