### ISSUE TITLE
maten op volgorde zetten

### ISSUE THREAD

**Issue by Tibo2008** [hans2103/xper-products.nl#5]
![image](https://github.com/hans2103/xper-products.nl/assets/167860003/022aaf95-d56a-460c-a2c2-052d2f003e2c)
maat 40cm staat nu boven 80cm niet op volgorde kun je die even omwisselen

**Comment by hans2103** [comment]
De titels staan alfabetisch gesorteerd. Daarom dat de volgorde als volgt is

- ZOS Gasslang 1
- ZOS Gasslang 1
- ZOS Gasslang 4
- ZOS Gasslang 8

![Scherm­afbeelding 2024-04-24 om 14 31 57](https://github.com/hans2103/xper-products.nl/assets/639822/5d5ac548-e6fb-4426-9e73-6cafef6c0a94)


Ik ga op onderzoek om na te gaan of we hier invloed op kunnen uitoefenen

**Comment by hans2103** [comment]
@Tibo2008 ik krijg niet gevonden hoe 125 na 80 kan laten sorteren. 
Mocht jij iets vinden hoor ik het graag. 
Als je het niet erg vind laten we het zoals het is.
