### ISSUE TITLE
product link

### ISSUE THREAD

**Issue by Tibo2008** [hans2103/xper-products.nl#6]
@hans2103 
![image](https://github.com/hans2103/xper-products.nl/assets/167860003/28014d36-cc3d-4d16-ab5e-2cc5b1d3dd53)
kan product link niet vinden

**Comment by hans2103** [comment]
@Tibo2008 het product kan ik in Magento beheer ook niet terugvinden. 

En bij het overzicht van ventilatoren staat deze er ook niet bij. Wel de 120T, 400-300-0163

https://www.onderdelenexpert.nl/installatiemateriaal/luchtafvoer/ventilator/zos


@jef8 is het product 400-300-0162 verwijderd van de shop?

**Comment by jef8** [comment]
@Tibo2008 @hans2103 Dit artikel is niet meer leverbaar . kan ook van de xper site verwijderd worden .

**Comment by hans2103** [comment]
pagina verwijderd
